import type { Locale } from "./config";

const en = {
  discover: "Discover", deals: "Deals", vendors: "Vendors", services: "Services",
  forPets: "For Pets", locations: "Locations", saved: "Saved", admin: "Admin",
  myPetSquare: "My PetSquare", signOut: "Sign out", signIn: "Sign in", forVendors: "For Vendors",
  toggleMenu: "Toggle menu", chooseLanguage: "Choose language",
  heroOne: "Discover better deals.", heroTwo: "Find trusted pet care.", heroThree: "Love your pet more.",
  heroBody: "Discover pet stores, products, services and exclusive deals from trusted vendors across Europe — all in one place.",
  searchPlaceholder: "Search products, services, breeds, vendors...", search: "Search",
  exploreDeals: "Explore Deals", findVendors: "Find Pet Vendors",
  signInDirectory: "Sign in required to unlock the full vendor directory & map.",
  dog: "Dog", cat: "Cat", verifiedAgo: "Verified 12 min ago", dogFoodBerlin: "Dog Food, Berlin",
} as const;

export type MessageKey = keyof typeof en;
type Messages = Record<MessageKey, string>;

const de: Messages = { discover:"Entdecken",deals:"Angebote",vendors:"Anbieter",services:"Dienstleistungen",forPets:"Für Haustiere",locations:"Standorte",saved:"Gespeichert",admin:"Admin",myPetSquare:"Mein PetSquare",signOut:"Abmelden",signIn:"Anmelden",forVendors:"Für Anbieter",toggleMenu:"Menü umschalten",chooseLanguage:"Sprache wählen",heroOne:"Bessere Angebote entdecken.",heroTwo:"Vertrauenswürdige Tierbetreuung finden.",heroThree:"Ihr Haustier noch mehr lieben.",heroBody:"Entdecken Sie Tierhandlungen, Produkte, Dienstleistungen und exklusive Angebote vertrauenswürdiger Anbieter in ganz Europa — alles an einem Ort.",searchPlaceholder:"Produkte, Dienstleistungen, Rassen, Anbieter suchen ...",search:"Suchen",exploreDeals:"Angebote entdecken",findVendors:"Tierbedarf-Anbieter finden",signInDirectory:"Melden Sie sich an, um das vollständige Anbieterverzeichnis und die Karte freizuschalten.",dog:"Hund",cat:"Katze",verifiedAgo:"Vor 12 Min. verifiziert",dogFoodBerlin:"Hundefutter, Berlin" };
const fr: Messages = { discover:"Découvrir",deals:"Offres",vendors:"Professionnels",services:"Services",forPets:"Pour les animaux",locations:"Localisations",saved:"Enregistrés",admin:"Admin",myPetSquare:"Mon PetSquare",signOut:"Se déconnecter",signIn:"Se connecter",forVendors:"Pour les professionnels",toggleMenu:"Ouvrir le menu",chooseLanguage:"Choisir la langue",heroOne:"Découvrez de meilleures offres.",heroTwo:"Trouvez des soins de confiance.",heroThree:"Aimez encore plus votre animal.",heroBody:"Découvrez des animaleries, produits, services et offres exclusives de professionnels de confiance partout en Europe — au même endroit.",searchPlaceholder:"Rechercher produits, services, races, professionnels...",search:"Rechercher",exploreDeals:"Explorer les offres",findVendors:"Trouver des professionnels",signInDirectory:"Connectez-vous pour accéder à l’annuaire complet et à la carte.",dog:"Chien",cat:"Chat",verifiedAgo:"Vérifié il y a 12 min",dogFoodBerlin:"Aliments pour chiens, Berlin" };
const it: Messages = { discover:"Scopri",deals:"Offerte",vendors:"Fornitori",services:"Servizi",forPets:"Per animali",locations:"Località",saved:"Salvati",admin:"Admin",myPetSquare:"Il mio PetSquare",signOut:"Esci",signIn:"Accedi",forVendors:"Per i fornitori",toggleMenu:"Apri il menu",chooseLanguage:"Scegli la lingua",heroOne:"Scopri offerte migliori.",heroTwo:"Trova cure affidabili.",heroThree:"Ama ancora di più il tuo animale.",heroBody:"Scopri negozi, prodotti, servizi e offerte esclusive di fornitori affidabili in tutta Europa — tutto in un unico posto.",searchPlaceholder:"Cerca prodotti, servizi, razze, fornitori...",search:"Cerca",exploreDeals:"Scopri le offerte",findVendors:"Trova fornitori per animali",signInDirectory:"Accedi per sbloccare l’elenco completo dei fornitori e la mappa.",dog:"Cane",cat:"Gatto",verifiedAgo:"Verificato 12 min fa",dogFoodBerlin:"Cibo per cani, Berlino" };
const es: Messages = { discover:"Descubrir",deals:"Ofertas",vendors:"Proveedores",services:"Servicios",forPets:"Para mascotas",locations:"Ubicaciones",saved:"Guardados",admin:"Admin",myPetSquare:"Mi PetSquare",signOut:"Cerrar sesión",signIn:"Iniciar sesión",forVendors:"Para proveedores",toggleMenu:"Abrir menú",chooseLanguage:"Elegir idioma",heroOne:"Descubre mejores ofertas.",heroTwo:"Encuentra cuidados de confianza.",heroThree:"Quiere aún más a tu mascota.",heroBody:"Descubre tiendas, productos, servicios y ofertas exclusivas de proveedores de confianza de toda Europa — todo en un solo lugar.",searchPlaceholder:"Buscar productos, servicios, razas, proveedores...",search:"Buscar",exploreDeals:"Explorar ofertas",findVendors:"Buscar proveedores para mascotas",signInDirectory:"Inicia sesión para acceder al directorio completo y al mapa.",dog:"Perro",cat:"Gato",verifiedAgo:"Verificado hace 12 min",dogFoodBerlin:"Comida para perros, Berlín" };
const pl: Messages = { discover:"Odkrywaj",deals:"Oferty",vendors:"Sprzedawcy",services:"Usługi",forPets:"Dla zwierząt",locations:"Lokalizacje",saved:"Zapisane",admin:"Admin",myPetSquare:"Mój PetSquare",signOut:"Wyloguj się",signIn:"Zaloguj się",forVendors:"Dla sprzedawców",toggleMenu:"Przełącz menu",chooseLanguage:"Wybierz język",heroOne:"Odkrywaj lepsze oferty.",heroTwo:"Znajdź godną zaufania opiekę.",heroThree:"Kochaj swojego pupila jeszcze bardziej.",heroBody:"Odkrywaj sklepy zoologiczne, produkty, usługi i wyjątkowe oferty od zaufanych sprzedawców z całej Europy — wszystko w jednym miejscu.",searchPlaceholder:"Szukaj produktów, usług, ras, sprzedawców...",search:"Szukaj",exploreDeals:"Przeglądaj oferty",findVendors:"Znajdź sprzedawców zoologicznych",signInDirectory:"Zaloguj się, aby uzyskać dostęp do pełnego katalogu i mapy.",dog:"Pies",cat:"Kot",verifiedAgo:"Zweryfikowano 12 min temu",dogFoodBerlin:"Karma dla psów, Berlin" };
const ro: Messages = { discover:"Descoperă",deals:"Oferte",vendors:"Furnizori",services:"Servicii",forPets:"Pentru animale",locations:"Locații",saved:"Salvate",admin:"Admin",myPetSquare:"PetSquare-ul meu",signOut:"Deconectare",signIn:"Autentificare",forVendors:"Pentru furnizori",toggleMenu:"Comută meniul",chooseLanguage:"Alege limba",heroOne:"Descoperă oferte mai bune.",heroTwo:"Găsește îngrijire de încredere.",heroThree:"Iubește-ți animalul și mai mult.",heroBody:"Descoperă magazine, produse, servicii și oferte exclusive de la furnizori de încredere din Europa — toate într-un singur loc.",searchPlaceholder:"Caută produse, servicii, rase, furnizori...",search:"Caută",exploreDeals:"Explorează ofertele",findVendors:"Găsește furnizori pentru animale",signInDirectory:"Autentifică-te pentru acces la directorul complet și hartă.",dog:"Câine",cat:"Pisică",verifiedAgo:"Verificat acum 12 min",dogFoodBerlin:"Hrană pentru câini, Berlin" };
const cs: Messages = { discover:"Objevovat",deals:"Nabídky",vendors:"Prodejci",services:"Služby",forPets:"Pro mazlíčky",locations:"Lokality",saved:"Uložené",admin:"Admin",myPetSquare:"Můj PetSquare",signOut:"Odhlásit se",signIn:"Přihlásit se",forVendors:"Pro prodejce",toggleMenu:"Přepnout nabídku",chooseLanguage:"Vybrat jazyk",heroOne:"Objevte lepší nabídky.",heroTwo:"Najděte důvěryhodnou péči.",heroThree:"Milujte svého mazlíčka ještě více.",heroBody:"Objevte obchody, produkty, služby a exkluzivní nabídky od důvěryhodných prodejců z celé Evropy — vše na jednom místě.",searchPlaceholder:"Hledat produkty, služby, plemena, prodejce...",search:"Hledat",exploreDeals:"Prozkoumat nabídky",findVendors:"Najít prodejce pro mazlíčky",signInDirectory:"Přihlaste se a odemkněte celý adresář a mapu.",dog:"Pes",cat:"Kočka",verifiedAgo:"Ověřeno před 12 min",dogFoodBerlin:"Krmivo pro psy, Berlín" };
const hu: Messages = { discover:"Felfedezés",deals:"Ajánlatok",vendors:"Szolgáltatók",services:"Szolgáltatások",forPets:"Kedvenceknek",locations:"Helyszínek",saved:"Mentett",admin:"Admin",myPetSquare:"Saját PetSquare",signOut:"Kijelentkezés",signIn:"Bejelentkezés",forVendors:"Szolgáltatóknak",toggleMenu:"Menü váltása",chooseLanguage:"Nyelv kiválasztása",heroOne:"Fedezz fel jobb ajánlatokat.",heroTwo:"Találj megbízható állatgondozást.",heroThree:"Szeresd még jobban kedvencedet.",heroBody:"Fedezz fel állatkereskedéseket, termékeket, szolgáltatásokat és exkluzív ajánlatokat megbízható európai szolgáltatóktól — mindent egy helyen.",searchPlaceholder:"Termékek, szolgáltatások, fajták, szolgáltatók keresése...",search:"Keresés",exploreDeals:"Ajánlatok felfedezése",findVendors:"Állatos szolgáltatók keresése",signInDirectory:"Jelentkezz be a teljes szolgáltatói címtár és térkép eléréséhez.",dog:"Kutya",cat:"Macska",verifiedAgo:"Ellenőrizve 12 perce",dogFoodBerlin:"Kutyatáp, Berlin" };
const pt: Messages = { discover:"Descobrir",deals:"Ofertas",vendors:"Fornecedores",services:"Serviços",forPets:"Para animais",locations:"Localizações",saved:"Guardados",admin:"Admin",myPetSquare:"O meu PetSquare",signOut:"Terminar sessão",signIn:"Iniciar sessão",forVendors:"Para fornecedores",toggleMenu:"Alternar menu",chooseLanguage:"Escolher idioma",heroOne:"Descubra melhores ofertas.",heroTwo:"Encontre cuidados de confiança.",heroThree:"Ame ainda mais o seu animal.",heroBody:"Descubra lojas, produtos, serviços e ofertas exclusivas de fornecedores de confiança em toda a Europa — tudo num só lugar.",searchPlaceholder:"Pesquisar produtos, serviços, raças, fornecedores...",search:"Pesquisar",exploreDeals:"Explorar ofertas",findVendors:"Encontrar fornecedores para animais",signInDirectory:"Inicie sessão para aceder ao diretório completo e ao mapa.",dog:"Cão",cat:"Gato",verifiedAgo:"Verificado há 12 min",dogFoodBerlin:"Comida para cães, Berlim" };

export const messages: Record<Locale, Messages> = { en, de, fr, it, es, pl, ro, cs, hu, pt };
