"use client";
import { useEffect, useRef, useState } from "react";
import { AlertTriangle, PawPrint, Send, Sparkles, UserRound } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
type Pet = { id: string; name: string; species: string; breed: string | null };
type Msg = { role: "user" | "assistant"; content: string };

function PawsperoMessage({ content }: { content: string }) {
  const clean = content.replace(/<br\s*\/?>/gi, "\n").replace(/\n{3,}/g, "\n\n").trim();
  return <div className="text-[0.925rem] leading-7 text-navy"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{
    h1: ({ children }) => <h2 className="mb-3 mt-1 font-display text-xl font-semibold">{children}</h2>, h2: ({ children }) => <h3 className="mb-2 mt-5 font-display text-lg font-semibold first:mt-0">{children}</h3>, h3: ({ children }) => <h4 className="mb-1.5 mt-4 font-semibold">{children}</h4>,
    p: ({ children }) => <p className="my-2 first:mt-0 last:mb-0">{children}</p>, ul: ({ children }) => <ul className="my-3 space-y-2 pl-1">{children}</ul>, ol: ({ children }) => <ol className="my-3 list-decimal space-y-2 pl-5 marker:font-semibold marker:text-tangerine">{children}</ol>, li: ({ children }) => <li className="relative pl-5 before:absolute before:left-0 before:top-[0.72rem] before:h-1.5 before:w-1.5 before:rounded-full before:bg-sage">{children}</li>,
    strong: ({ children }) => <strong className="font-semibold">{children}</strong>, blockquote: ({ children }) => <blockquote className="my-4 rounded-r-xl border-l-4 border-sage bg-sage-light px-4 py-2 text-navy/80">{children}</blockquote>,
    table: ({ children }) => <div className="my-4 overflow-x-auto rounded-xl border border-paper-dim"><table className="w-full min-w-[480px] border-collapse text-left text-sm">{children}</table></div>, thead: ({ children }) => <thead className="bg-sage-light">{children}</thead>, th: ({ children }) => <th className="border-b border-paper-dim px-3 py-2 font-semibold">{children}</th>, td: ({ children }) => <td className="border-b border-paper-dim px-3 py-2 align-top">{children}</td>,
    a: ({ href, children }) => <a href={href} target="_blank" rel="noreferrer" className="font-medium text-tangerine underline decoration-tangerine/30 underline-offset-4">{children}</a>, code: ({ children }) => <code className="rounded bg-paper-dim px-1.5 py-0.5 font-data text-[0.85em]">{children}</code>,
  }}>{clean}</ReactMarkdown></div>;
}

export default function AssistantChat({ pets }: { pets: Pet[] }) {
  const [petId, setPetId] = useState(pets[0]?.id ?? "");
  const [messages, setMessages] = useState<Msg[]>([{ role: "assistant", content: pets[0] ? `Hi, I’m **Pawspero**. I’m ready to help you care for **${pets[0].name}**. What would you like to know?` : "Hi, I’m **Pawspero**, your PetSquare companion. Ask me about pet care, feeding, products, or everyday wellbeing." }]);
  const [input, setInput] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const endRef = useRef<HTMLDivElement>(null);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, loading]);
  const selectedPet = pets.find((pet) => pet.id === petId);
  async function send() { const text = input.trim(); if (!text || loading) return; const next = [...messages, { role: "user" as const, content: text }]; setMessages(next); setInput(""); setLoading(true); setError(null); try { const response = await fetch("/api/assistant", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: next, pet: selectedPet ? { name: selectedPet.name, species: selectedPet.species, breed: selectedPet.breed } : undefined }) }); const data = await response.json().catch(() => ({ error: "Pawspero returned an invalid response." })); if (!response.ok) throw new Error(data.error || "Something went wrong."); setMessages((current) => [...current, { role: "assistant", content: data.reply }]); } catch (reason) { setError(reason instanceof Error ? reason.message : "Something went wrong."); } finally { setLoading(false); } }
  return <div className="mt-5 flex min-h-0 flex-1 flex-col overflow-hidden rounded-[1.75rem] border border-paper-dim bg-surface shadow-[var(--shadow-card)]">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-paper-dim bg-gradient-to-r from-sage-light to-surface px-5 py-4"><div className="flex items-center gap-3"><div className="relative flex h-11 w-11 items-center justify-center rounded-2xl bg-tangerine text-white shadow-sm"><PawPrint className="h-5 w-5" /><span className="absolute -right-1 -top-1 h-3 w-3 rounded-full border-2 border-surface bg-sage" /></div><div><div className="flex items-center gap-1.5"><h2 className="font-display text-lg font-semibold text-navy">Pawspero</h2><Sparkles className="h-3.5 w-3.5 text-sunshine" /></div><p className="text-xs text-navy/50">Your thoughtful pet-care companion</p></div></div>{pets.length > 0 && <label className="flex items-center gap-2 text-xs text-navy/50">Helping with <select value={petId} onChange={(event) => setPetId(event.target.value)} className="rounded-full border border-paper-dim bg-surface px-3 py-1.5 font-medium text-navy outline-none focus:ring-2 focus:ring-tangerine/30">{pets.map((pet) => <option key={pet.id} value={pet.id}>{pet.name} · {pet.species}</option>)}</select></label>}</div>
    <div className="flex-1 space-y-5 overflow-y-auto bg-paper/45 p-4 sm:p-6">{messages.map((message, index) => <div key={index} className={`flex items-start gap-2.5 ${message.role === "user" ? "flex-row-reverse" : ""}`}><div className={`mt-1 flex h-8 w-8 shrink-0 items-center justify-center rounded-xl ${message.role === "user" ? "bg-navy text-paper" : "bg-sage-light text-sage"}`}>{message.role === "user" ? <UserRound className="h-4 w-4" /> : <PawPrint className="h-4 w-4" />}</div><div className={`max-w-[min(88%,52rem)] rounded-2xl px-4 py-3 shadow-sm sm:px-5 ${message.role === "user" ? "rounded-tr-md bg-tangerine text-white" : "rounded-tl-md border border-paper-dim bg-surface"}`}>{message.role === "assistant" ? <PawsperoMessage content={message.content} /> : <p className="whitespace-pre-wrap text-sm leading-6">{message.content}</p>}</div></div>)}{loading && <div className="flex items-start gap-2.5"><div className="flex h-8 w-8 items-center justify-center rounded-xl bg-sage-light text-sage"><PawPrint className="h-4 w-4" /></div><div className="flex items-center gap-1.5 rounded-2xl rounded-tl-md border border-paper-dim bg-surface px-4 py-3" aria-label="Pawspero is thinking"><span className="h-2 w-2 animate-bounce rounded-full bg-sage [animation-delay:-.3s]" /><span className="h-2 w-2 animate-bounce rounded-full bg-sage [animation-delay:-.15s]" /><span className="h-2 w-2 animate-bounce rounded-full bg-sage" /></div></div>}{error && <div role="alert" className="flex items-start gap-2 rounded-xl border border-coral/20 bg-coral/10 p-3 text-sm text-coral"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" /> {error}</div>}<div ref={endRef} /></div>
    <div className="border-t border-paper-dim bg-surface p-3 sm:p-4"><div className="flex items-end gap-2 rounded-2xl border border-paper-dim bg-paper px-4 py-2 focus-within:border-tangerine/50 focus-within:ring-2 focus-within:ring-tangerine/15"><textarea value={input} rows={1} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } }} placeholder={selectedPet ? `Ask Pawspero about ${selectedPet.name}…` : "Ask Pawspero about your pet…"} className="max-h-32 min-h-10 flex-1 resize-none bg-transparent py-2 text-sm text-navy outline-none placeholder:text-navy/35" /><button type="button" onClick={() => void send()} disabled={loading || !input.trim()} aria-label="Send message to Pawspero" className="mb-0.5 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-tangerine text-white shadow-sm transition hover:bg-tangerine-light disabled:cursor-not-allowed disabled:opacity-40"><Send className="h-4 w-4" /></button></div><p className="mt-2 text-center text-[0.68rem] text-navy/35">Pawspero can make mistakes. Consult a veterinarian for medical advice.</p></div>
  </div>;
}
